import {RenderProps} from '../types';

export const sampleRenderProps: RenderProps = {
  runId: 'sample-run',
  title: '海の深さって、想像よりずっと極端',
  timeline: {
    totalDurationMs: 28000,
    segments: [
      {
        sectionType: 'hook',
        startMs: 0,
        endMs: 5000,
        audioPath: 'https://www.soundjay.com/button/beep-07.wav',
        audioPublicPath: 'https://www.soundjay.com/button/beep-07.wav',
        caption: '実は海、想像よりずっと極端',
        highlight: '海',
        backgroundAsset: 'https://picsum.photos/seed/ocean-1/1080/1920',
        backgroundAssetType: 'image',
      },
      {
        sectionType: 'segment',
        startMs: 5000,
        endMs: 11000,
        audioPath: 'https://www.soundjay.com/button/beep-07.wav',
        audioPublicPath: 'https://www.soundjay.com/button/beep-07.wav',
        caption: '光が届くのはほんの一部',
        highlight: '光',
        backgroundAsset: 'https://picsum.photos/seed/ocean-2/1080/1920',
        backgroundAssetType: 'image',
      },
      {
        sectionType: 'segment',
        startMs: 11000,
        endMs: 18000,
        audioPath: 'https://www.soundjay.com/button/beep-07.wav',
        audioPublicPath: 'https://www.soundjay.com/button/beep-07.wav',
        caption: '深海の圧力は常識を壊す',
        highlight: '深海',
        backgroundAsset: 'https://picsum.photos/seed/ocean-3/1080/1920',
        backgroundAssetType: 'image',
      },
      {
        sectionType: 'segment',
        startMs: 18000,
        endMs: 24000,
        audioPath: 'https://www.soundjay.com/button/beep-07.wav',
        audioPublicPath: 'https://www.soundjay.com/button/beep-07.wav',
        caption: 'それでも生きる生物がいる',
        highlight: '生物',
        backgroundAsset: 'https://picsum.photos/seed/ocean-4/1080/1920',
        backgroundAssetType: 'image',
      },
      {
        sectionType: 'cta',
        startMs: 24000,
        endMs: 28000,
        audioPath: 'https://www.soundjay.com/button/beep-07.wav',
        audioPublicPath: 'https://www.soundjay.com/button/beep-07.wav',
        caption: '保存して寝る前に見返して',
        highlight: '保存',
        backgroundAsset: 'https://picsum.photos/seed/ocean-5/1080/1920',
        backgroundAssetType: 'image',
      },
    ],
  },
};
